version: '3.9'

services:
  django:
    build:
      context: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn -c gunicorn.conf.py"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    env_file:
      - ./env/.env.dev

  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
    depends_on:
      - django

  acme-companion:
    image: nginxproxy/acme-companion
    env_file:
      - ./env/.env.staging.proxy-companion
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
      - vhost:/etc/nginx/vhost.d
    depends_on:
      - nginx-proxy

volumes:
  static_volume:
  media_volume:
  certs:
  html:
  acme:
  vhost: