version: '3.9'

services:
  django:
    build:
      context: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn -c gunicorn.conf.py"
    env_file:
      - ./env/.env.dev

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_volume:/etc/nginx/conf.d
      - certbot_certificates:/etc/letsencrypt
      - certbot_challenge:/var/www/certbot
    env_file:
      - ./env/.env.nginx
    depends_on:
      - django

volumes:
  nginx_volume:
  certbot_challenge:
  certbot_certificates:
