"""
Django settings for majestic project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from better_pyenv import Env

# Read environment variables from .env file
env = Env()
env.read_env(".env.dev", recurse=False)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=False)

if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
elif env.bool("TESTING"):
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ['erbfq2dzvb.us-east-2.awsapprunner.com', 'bjmajestic.com', 'www.bjmajestic.com']

CSRF_TRUSTED_ORIGINS = ['https://erbfq2dzvb.us-east-2.awsapprunner.com', 'https://bjmajestic.com', 'https://www.bjmajestic.com']

# Application definition

INSTALLED_APPS = [
    # Majestic apps
    'products',
    'contact_us',
    'about',
    'catalog',
    # Cloud storage
    'storages',
    # File cleanup
    'django_cleanup',
    # Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'majestic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.media',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'majestic.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# Superuser initialization variables
SUPERUSER_USERNAME = env.str("SUPERUSER_USERNAME")
SUPERUSER_PASSWORD = env.str("SUPERUSER_PASSWORD")

USE_POSTGRESQL = env.bool("USE_POSTGRESQL", default=False)

if USE_POSTGRESQL:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env.str('POSTGRES_DBNAME'),
            "USER": "postgres",
            "PASSWORD": env.str('POSTGRES_PASSWORD'),
            # set in docker-compose.yml
            "HOST": env.str('POSTGRES_DBHOST'),
            "PORT": env.str('POSTGRES_DBPORT'),  # default postgres port
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

USE_STORAGE = env.str("USE_STORAGE")

# Assets setting (static files and image files)
if USE_STORAGE == "azure":
    """Configure Azure storage for static and media files.
    """
    DEFAULT_FILE_STORAGE = 'majestic.custom_storage.MediaAzureStorage'
    STATICFILES_STORAGE = 'majestic.custom_storage.StaticAzureStorage'
    AZURE_ACCOUNT_NAME = env.str('AZURE_ACCOUNT_NAME')
    AZURE_ACCOUNT_KEY = env.str('AZURE_ACCOUNT_KEY')
    AZURE_OVERWRITE_FILES = True
elif USE_STORAGE == "s3":
    """ Configure S3 storage for static and media files.
    """
    AWS_ACCESS_KEY_ID = env.str('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env.str('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = env.str('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_CUSTOM_DOMAIN = env.str('AWS_S3_CUSTOM_DOMAIN')
    # Static files
    AWS_LOCATION = 'static'
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'
    STATICFILES_STORAGE = 'majestic.custom_storage.StaticS3Storage'
    # Public media files
    PUBLIC_MEDIA_LOCATION = 'media'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/'
    DEFAULT_FILE_STORAGE = 'majestic.custom_storage.PublicMediaS3Storage'
    # Private media files
    Private_MEDIA_LOCATION = 'private'
    PRIVATE_FILE_STORAGE = 'majestic.custom_storage.PrivateMediaS3Storage'
else:
    """Configure local storage for static and media files.
    """
    # Static files
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')
    STATIC_URL = '/static/'
    # Media files
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
    MEDIA_URL = '/media/'

# Email settings
USE_SMTP = env.bool('USE_SMTP')

if USE_SMTP:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    DEFAULT_FROM_EMAIL = env.str('DEFAULT_FROM_EMAIL')
    EMAIL_HOST = 'smtp.sendgrid.net'
    EMAIL_HOST_USER = env.str('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = env.str('EMAIL_HOST_PASSWORD')
    EMAIL_PORT = '465'
    EMAIL_USE_SSL = True
    DEFAULT_TO_EMAIL = env.str('DEFAULT_TO_EMAIL')
else:
    DEFAULT_FROM_EMAIL = 'contact@example.com'
    DEFAULT_TO_EMAIL = 'manager@example.com'
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
