# Generated by Django 4.0.6 on 2022-08-08 23:51

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(unique=True)),
                ('file', models.FileField(upload_to='catalogs/%Y/', validators=[catalog.models.validate_file_extension])),
            ],
        ),
    ]
