# Generated by Django 3.0.5 on 2020-05-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(height_field='100', upload_to='uploads/%Y/%m/%d/', width_field='100'),
        ),
    ]
