# Generated by Django 3.0.5 on 2020-05-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200525_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
