# Generated by Django 3.0.7 on 2020-06-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productphoto',
            options={'verbose_name_plural': 'Product Photos'},
        ),
    ]
