# Generated by Django 3.1.5 on 2021-05-25 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
    ]
