# Generated by Django 3.1.5 on 2021-05-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210524_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='low_price',
        ),
    ]
