# Generated by Django 4.0.4 on 2022-05-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210525_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
