# Generated by Django 4.0.4 on 2022-06-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_about_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
